name: Build and Test on Hardware

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build_and_test:
    runs-on: self-hosted
    # The 'if' will prevent running this job if from a fork pull request
    if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build test project
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4.1
        target: esp32s3
        path: 'examples/test'
    - name: Flash and Test
      run: |
        cd examples/test
        idf.py flash -p $CI_ESP32_PORT && python verify_serial_output.py $CI_ESP32_PORT
