name: Test on Hardware

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build_test_example:
    runs-on: ubuntu-latest
    # The 'if' will prevent running this job if from a fork pull request
    if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: 'x64'
    - name: Build test project
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4.1
        target: esp32s3
        path: 'examples/test'
    - name: Create build tarball
      run: |
          cd examples/test
          ./tar_build.sh
    - name: Upload build tarball artifact
      uses: actions/upload-artifact@v3
      with:
          name: build.tar.gz
          path: examples/test/build.tar.gz

  flash_and_test:
    needs: build_test_example
    runs-on: self-hosted
    # The 'if' will prevent running this job if from a fork pull request
    if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
    steps:
    - name: Download build tarball artifact
      uses: actions/download-artifact@v3
      with:
          name: build.tar.gz
    - name: Untar build tarball
      run: tar xvf build.tar.gz
    - name: List files
      run: |
          ls -R build
    # - name: Flash and Test
    #   run: |
    #     cd examples/test
    #     idf.py flash -p $CI_ESP32_PORT && python verify_serial_output.py $CI_ESP32_PORT
